POST http://localhost:8080/registration
Content-Type: application/x-www-form-urlencoded

name=MyName&login=easyLogin&password=easyPassword

###

POST http://localhost:8080/authorization
Content-Type: application/x-www-form-urlencoded

login=easyLogin&password=easyPassword

###

POST http://localhost:8080/calc
Content-Type: application/x-www-form-urlencoded

num1=21&num2=14&operand=sum

###

GET http://localhost:8080/history

###

POST http://localhost:8080/logout
